In [1]:
import pandas as pd
import numpy as np

In [39]:
df=pd.read_csv('train.csv')

In [40]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [41]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [42]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [43]:
df.shape

(891, 8)

In [44]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [45]:
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [52]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.25,random_state=42)

In [55]:
X_train.shape

(668, 7)

In [56]:
si_age=SimpleImputer()
si_embarked=SimpleImputer(strategy='most_frequent')

X_train_age=si_age.fit_transform(X_train[['Age']])
X_train_embarked=si_embarked.fit_transform(X_train[['Embarked']])

X_test_age=si_age.fit_transform(X_test[['Age']])
X_test_embarked=si_embarked.fit_transform(X_test[['Embarked']])

In [59]:
ohe_sex=OneHotEncoder(sparse=False,handle_unknown='ignore')
ohe_embarked=OneHotEncoder(sparse=False,handle_unknown='ignore')

X_train_sex=ohe_sex.fit_transform(X_train[['Sex']])
X_train_embarked=ohe_embarked.fit_transform(X_train_embarked)

X_test_sex=ohe_sex.fit_transform(X_test[['Sex']])
X_test_embarked=ohe_embarked.fit_transform(X_test_embarked)

In [60]:
X_train_rem=X_train.drop(columns=["Sex","Age","Embarked"])
X_test_rem=X_test.drop(columns=["Sex","Age","Embarked"])

In [61]:
X_train_transformed=np.concatenate((X_train_rem,X_train_age,X_train_sex,X_train_embarked),axis=1)
X_test_transformed=np.concatenate((X_test_rem,X_test_age,X_test_sex,X_test_embarked),axis=1)

In [62]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()

In [63]:
nb.fit(X_train_transformed,y_train)

GaussianNB()

In [64]:
y_pred=nb.predict(X_test_transformed)

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7802690582959642

In [67]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)

In [88]:
clf.fit(X_train_transformed,y_train)
X_train_transformed

array([[1., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [2., 0., 2., ..., 0., 0., 1.],
       ...,
       [3., 2., 0., ..., 0., 0., 1.],
       [1., 1., 2., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 1.]])

In [69]:
y_pred2=clf.predict(X_test_transformed)

In [70]:
accuracy_score(y_test,y_pred2)

0.7847533632286996

In [71]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression(random_state=0)

In [72]:
lg.fit(X_train_transformed,y_train)
y_pred3=lg.predict(X_test_transformed)

c:\users\krish\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [73]:
accuracy_score(y_test,y_pred3)

0.8026905829596412

In [74]:
test_df=pd.read_csv('test.csv')

In [75]:
test_df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [76]:
test_df.head()

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       3    male  34.5      0      0   7.8292        Q
1       3  female  47.0      1      0   7.0000        S
2       2    male  62.0      0      0   9.6875        Q
3       3    male  27.0      0      0   8.6625        S
4       3  female  22.0      1      1  12.2875        S

In [77]:
test_df.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [1]:
testing_age=si_age.fit_transform(test_df[['Age']])
testing_embarked=si_embarked.fit_transform(test_df[['Embarked']])
testing_fare=si_embarked.fit_transform(test_df[['Fare']])


NameError: name 'si_age' is not defined

In [82]:
testing_sex=ohe_sex.fit_transform(test_df[['Sex']])
testing_embarked=ohe_embarked.fit_transform(test_df[["Embarked"]])

In [83]:
testing_embarked

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [97]:
testing_rem=test_df.drop(columns=["Sex","Age","Embarked"])
testing_rem.isnull().sum()


Pclass    0
SibSp     0
Parch     0
Fare      1
dtype: int64

In [85]:
testing_transformed=np.concatenate((testing_rem,testing_age,testing_sex,testing_embarked),axis=1)

In [92]:
testing_transformed

array([[3., 0., 0., ..., 0., 1., 0.],
       [3., 1., 0., ..., 0., 0., 1.],
       [2., 0., 0., ..., 0., 1., 0.],
       ...,
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [3., 1., 1., ..., 1., 0., 0.]])